channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=22.3.1
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - numpy==1.25.0
  - packaging==23.0
  - psutil==5.9.4
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
